### PR TITLE
feat: user can delete tags.

### PR DESCRIPTION
**Pull request by CheoR**
# Description

Only staff can delete tags.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# Testing Instructions

`git fetch --all`
`git checkout cr-tags-delete`
`python3 manage.py runserver`

See client-side pull request for frontend instructions.

As logged in staff:

In Postman, make a `GET` request to

`http://localhost:8000/tags`

To view all tags then make a `DELETE` request with an available id

`http://localhost:8000/tags/${id}`

and another `GET` request to confirm tag was deleted.

As logged in non-staff:

In Postman, make a `GET` request to

`http://localhost:8000/tags`

To view all tags then make a `DELETE` request with an available id

`http://localhost:8000/tags/${id}`

You should receive a `403` error.

In browswer, after logging in, click on `Tag Management` link and delete a tag.
Tag list should update.

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by phillipphan — APPROVED** [review]
i can delete tags

**Review by Daniel-L-Ross — CHANGES_REQUESTED** [review]
I was able to delete the tag as a regular author. I think only admin are allowed to delete tags.

**Comment by CheoR** [comment]
@Daniel-L-Ross  Now only staff/admin can delete tags.

**Review by Daniel-L-Ross — COMMENTED** [review]
@CheoR I'm still able to delete tags as a normal user. 
I ran git fetch --all and git pull origin cr-tags-delete, so I  have the most recent code. Not sure why I'm not seeing the changes.

**Pull request merged**
