### PR TITLE
Cr categories delete

### LINKED ISSUE #16: Delete a Category
As an admin I would like to be able to delete a Category so that I can remove any that are not needed.

**Given** an admin is vising the list of Categories  
**When** they select the `Delete` option  
**Then** they should be prompted to confirm the deletion  

**Given** the admin wishes to confirm the delete  
**When** they the select the option to confirm  
**Then** the Category should be removed from the system  
**And** the admin should be directed back to the Category list  

**Given** the admin decides not to confirm the delete  
**When** they the select the option to reject confirmation  
**Then** the Category should NOT be removed from the system  
**And** the admin should be directed back to the Category list  

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

### LINKED ISSUE #17: Edit a Category
As an admin I would like to be able to modify a Category so that I can rephrase the name if I think of something more appropriate.

**Given** the user is viewing the Category list  
**When** they select the option to edit an Category  
**Then** the user should be directed to a form and given the ability to change the Category's name  

**Given** the user is finished updating the Category information  
**When** they click the `Save` button  
**Then** the updated Category should be saved to the database  
**And** the user should be redirected to the new Category List page  

**Given** the user has decided not to edit the Category  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

### PR DESCRIPTION
**Pull request by CheoR**
# Description

Staff can edit tags.
Closes #16 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# Testing Instructions

`git fetch --all`
`git checkout cr-categories-edit`
`python3 manage runserver`

For client-side instructions, see frontend pull request.

In Postman, change Authentication token to staff user.

Make a `GET` request to `http://localhost:8000/categories/5` to view its label.

Then make a `PUT` request to `http://localhost:8000/categories/5` with the following in the body.

{
  "label": "new label"
}

then make a new `GET` request to view updated label.

 Change Authentication token to non-staff user and follow instructions above. User will receive a non-authorized error.

When logged in as staff, click on "Tag Management" and there will be an option to edit a tag.
Click on `Edit` to view tag form to update.
Change current label.
When click on `Update`, user will see tag updated.

When logged in as non-staff, `Edit` option is unavailable.

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [X] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by phillipphan — CHANGES_REQUESTED** [review]
there is no update method for categories or tags on this branch

**Comment by CheoR** [comment]
Correction, it's #16 delete category, not #17 edit category.

**Review by phillipphan — APPROVED** [review]
i can delete categories

**Review by Daniel-L-Ross — APPROVED** [review]
Looks good!

**Pull request merged**
